title: HumanityGrid
description: "HumanityGrid is a community-driven platform leveraging distributed computing and AI to solve global challenges."
baseurl: "/humanitygrid"
url: "https://richudell.github.io"
theme: minima

markdown: kramdown
