name: Update Wiki Footer

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-footer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest version which uses Node.js 20

      - name: Calculate stats
        id: calculate-stats
        run: |
          FILE_COUNT=$(find . -type f | wc -l)
          LINE_COUNT=$(find . -type f -name "*.cs" -exec wc -l {} + | awk '{s+=$1} END {print s}')
          COMMIT_COUNT=$(git rev-list --count HEAD)
          CONTRIBUTORS=$(git shortlog -sn | wc -l)

          echo "FILE_COUNT=$FILE_COUNT" >> $GITHUB_ENV
          echo "LINE_COUNT=$LINE_COUNT" >> $GITHUB_ENV
          echo "COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV
          echo "CONTRIBUTORS=$CONTRIBUTORS" >> $GITHUB_ENV

      - name: Clone the Wiki repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.wiki.git wiki
          cd wiki

      - name: Update wiki footer
        env:
          FILE_COUNT: ${{ env.FILE_COUNT }}
          LINE_COUNT: ${{ env.LINE_COUNT }}
          COMMIT_COUNT: ${{ env.COMMIT_COUNT }}
          CONTRIBUTORS: ${{ env.CONTRIBUTORS }}
        run: |
          FOOTER="## Project Stats\n\n"
          FOOTER+="* Total Files: $FILE_COUNT\n"
          FOOTER+="* Total Lines of Code: $LINE_COUNT\n"
          FOOTER+="* Total Commits: $COMMIT_COUNT\n"
          FOOTER+="* Contributors: $CONTRIBUTORS\n"

          echo -e "$FOOTER" > wiki/Footer.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd wiki
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add Footer.md
          git commit -m "Update wiki footer with latest stats"
          git push
